apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wise-eat

resources:
  - limitrange.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - poddisruptionbudget.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: wise-eat
  app.kubernetes.io/managed-by: kustomize

images:
  - name: africa-meals/api
    newName: africa-meals/api
    newTag: latest
