apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: africa-meals-api
  namespace: wise-eat
  labels:
    app.kubernetes.io/name: africa-meals-api
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: africa-meals-api
