; TLS front-end cache Redis réplica 1 — Let's Encrypt via /etc/stunnel/certs/
[redis-cache-replica-1]
accept = 6383
connect = 127.0.0.1:6371
cert = /etc/stunnel/certs/fullchain.pem
key = /etc/stunnel/certs/privkey.pem

[redis-cache-replica-1-v6]
accept = :::6383
connect = 127.0.0.1:6371
cert = /etc/stunnel/certs/fullchain.pem
key = /etc/stunnel/certs/privkey.pem
