; TLS front-end BullMQ Redis — Let's Encrypt via /etc/stunnel/certs/
; IPv4 explicite (0.0.0.0) — pods k3s via cni0 ; IPv6 :::PORT avec bindv6only=1.
[redis-bullmq]
accept = 0.0.0.0:6382
connect = 127.0.0.1:6380
cert = /etc/stunnel/certs/fullchain.pem
key = /etc/stunnel/certs/privkey.pem

[redis-bullmq-v6]
accept = :::6382
connect = 127.0.0.1:6380
cert = /etc/stunnel/certs/fullchain.pem
key = /etc/stunnel/certs/privkey.pem
