; TLS front-end cache Redis réplica 2 — Let's Encrypt via /etc/stunnel/certs/
[redis-cache-replica-2]
accept = 6384
connect = 127.0.0.1:6372
cert = /etc/stunnel/certs/fullchain.pem
key = /etc/stunnel/certs/privkey.pem

[redis-cache-replica-2-v6]
accept = [::]:6384
connect = 127.0.0.1:6372
cert = /etc/stunnel/certs/fullchain.pem
key = /etc/stunnel/certs/privkey.pem
