; TLS front-end cache Redis — Let's Encrypt via /etc/stunnel/certs/
; IPv4 explicite (0.0.0.0) — pods k3s via cni0 ; IPv6 :::PORT avec bindv6only=1.
[redis-cache]
accept = 0.0.0.0:6381
connect = 127.0.0.1:6379
cert = /etc/stunnel/certs/fullchain.pem
key = /etc/stunnel/certs/privkey.pem

[redis-cache-v6]
accept = :::6381
connect = 127.0.0.1:6379
cert = /etc/stunnel/certs/fullchain.pem
key = /etc/stunnel/certs/privkey.pem
