apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wise-eat

resources:
  - deployment-minio.yaml
  - deployment-minio-replica-1.yaml
  - deployment-minio-replica-2.yaml
  - service-minio.yaml
  - service-minio-replica-1.yaml
  - service-minio-replica-2.yaml

commonLabels:
  app.kubernetes.io/part-of: wise-eat
  app.kubernetes.io/managed-by: kustomize

images:
  - name: minio/minio
    newName: minio/minio
    newTag: RELEASE.2024-11-07T00-52-20Z
