apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wise-eat

resources:
  - deployment-mongo-1.yaml
  - deployment-mongo-2.yaml
  - deployment-mongo-3.yaml
  - service-mongo-1.yaml
  - service-mongo-2.yaml
  - service-mongo-3.yaml

commonLabels:
  app.kubernetes.io/part-of: wise-eat
  app.kubernetes.io/managed-by: kustomize

images:
  - name: mongo
    newName: mongo
    newTag: "8.0"
