; TLS front-end Memcached — Let's Encrypt via /etc/stunnel/certs/
; IPv4 explicite (0.0.0.0) — pods k3s via cni0 ; IPv6 :::PORT avec bindv6only=1.
[memcached-tls]
accept = 0.0.0.0:11212
connect = 127.0.0.1:11211
cert = /etc/stunnel/certs/fullchain.pem
key = /etc/stunnel/certs/privkey.pem

[memcached-tls-v6]
accept = :::11212
connect = 127.0.0.1:11211
cert = /etc/stunnel/certs/fullchain.pem
key = /etc/stunnel/certs/privkey.pem
