apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wise-eat

resources:
  - deployment-memcached.yaml
  - deployment-memcached-replica-1.yaml
  - deployment-memcached-replica-2.yaml
  - service-memcached.yaml
  - service-memcached-replica-1.yaml
  - service-memcached-replica-2.yaml

commonLabels:
  app.kubernetes.io/part-of: wise-eat
  app.kubernetes.io/managed-by: kustomize

images:
  - name: memcached
    newName: memcached
    newTag: 1.6-alpine
