apiVersion: v1
kind: Service
metadata:
  name: memcached-replica-1
  namespace: wise-eat
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/component: cache
    app.kubernetes.io/instance: replica-1
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: replica-1
  ports:
    - name: memcached
      port: 11211
      targetPort: memcached
      protocol: TCP
