apiVersion: v1
kind: Service
metadata:
  name: africa-meals-ws
  namespace: wise-eat
  labels:
    app.kubernetes.io/name: africa-meals-ws
    app.kubernetes.io/component: websocket
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: africa-meals-ws
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30800
      protocol: TCP
