global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: redis-cache
    static_configs:
      - targets: ['redis-exporter-cache:9121']
        labels:
          namespace: wise-eat
          redis_cluster: a
          redis_instance: cache
          redis_port: '6379'

  - job_name: redis-bullmq
    static_configs:
      - targets: ['redis-exporter-bullmq:9121']
        labels:
          namespace: wise-eat
          redis_cluster: a
          redis_instance: bullmq
          redis_port: '6380'

  - job_name: memcached
    static_configs:
      - targets: ['memcached-exporter:9150']
        labels:
          namespace: wise-eat
          memcached_cluster: a
          memcached_port: '11211'

  - job_name: redis-cache-replica
    static_configs:
      - targets: ['redis-exporter-cache-replica:9121']
        labels:
          namespace: wise-eat
          redis_cluster: b
          redis_instance: cache-replica
          redis_port: '6371'

  - job_name: redis-bullmq-replica
    static_configs:
      - targets: ['redis-exporter-bullmq-replica:9121']
        labels:
          namespace: wise-eat
          redis_cluster: b
          redis_instance: bullmq-replica
          redis_port: '6390'

  - job_name: memcached-b
    static_configs:
      - targets: ['memcached-exporter-b:9150']
        labels:
          namespace: wise-eat
          memcached_cluster: b
          memcached_port: '11213'
